repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:

      - id: format-xml
        name: format xml with xmllint
        entry: .pre-commit/format-xml.sh
        language: script
        types: [xml]

      - id: format-json
        name: format json with jq
        entry: .pre-commit/format-json.sh
        language: script
        types: [json]

      - id: flag-remove-shadow
        name: no Shadow flag outside shadows directories
        entry: .pre-commit/flag-remove-shadow.sh
        language: script
        types: [json]
        exclude: shadows/

      - id: sync-shadow-configs
        name: sync shadow configs from no_shadows
        entry: .pre-commit/sync-shadow-configs.sh
        language: script
        types: [json]
        files: no_shadows/

      - id: flag-add-shadow
        name: require Shadow flag in shadows directories
        entry: .pre-commit/flag-add-shadow.sh
        language: script
        types: [json]
        files: shadows/

      - id: flag-add-noexternalemittance
        name: ensure NoExternalEmittance on lights
        entry: .pre-commit/flag-add-noexternalemittance.sh
        language: script
        types: [json]
        exclude: windows_helios/

      - id: sync-windows-helios
        name: sync windows configs to windows_helios
        entry: .pre-commit/sync-windows-helios.sh
        language: script
        types: [json]
        files: windows/

      - id: match-shadow-filenames
        name: match filenames between no_shadows and shadows
        entry: .pre-commit/match-shadow-filenames.sh
        language: script
        pass_filenames: false
        always_run: true

      - id: validate-fomod
        name: validate fomod
        entry: .pre-commit/validate-fomod.sh
        language: script
        types: [xml]
        files: fomod/ModuleConfig\.xml$
