repos:
  - repo: local
    hooks:
      - id: no-shadow-flag
        name: no Shadow flag outside shadows directories
        entry: .pre-commit-hooks/no-shadow-flag.sh
        language: script
        types: [json]
        exclude: shadows/
      - id: sync-shadow-configs
        name: sync shadow configs from no_shadows
        entry: .pre-commit-hooks/sync-shadow-configs.sh
        language: script
        types: [json]
        files: no_shadows/
      - id: format-json
        name: format json with jq
        entry: .pre-commit-hooks/format-json.sh
        language: script
        types: [json]
      - id: format-xml
        name: format xml with xmllint
        entry: .pre-commit-hooks/format-xml.sh
        language: script
        types: [xml]
