[Forms]
; Use embers with smaller flames in Sky Haven Temple
; so we can use the same brightness for extinguished
; and burning embers.
FXfireWithEmbersHeavyToggle|FXfireWithEmbers02Toggle

[Forms|WinterholdCollegeMiddenLocation,IlinaltasDeepLocation,FellglowKeepLocation,WindhelmPalaceOfTheKingsLocation,WindhelmTempleOfTalosLocation,KilkreathRuinsLocation,WhiterunHouseoftheDeadLocation,PotemasCatacombsLocation,NightcallerTempleLocation,SnowVeilSanctumLocation,ForelhostLocation,SaarthalLocation,BrokenTowerRedoubtLocation]
; Since Based Lighting ignites all candles, we need to visit areas that have so
; many candles in them that it either kills FPS or causes overexposure.
; origBaseID|swapBaseID|propertyOverrides|chance
RuinsFloorCandleLampSmallOn|RuinsFloorCandleLampSmallOff|NONE|chance(75.0)
RuinsFloorCandleLampSmallOn02|RuinsFloorCandleLampSmallOff02|NONE|chance(75.0)
RuinsFloorCandleLampMidOn|RuinsFloorCandleLampMidOff|NONE|chance(75.0)
RuinsFloorCandleLampMidOn02|RuinsFloorCandleLampMidOff02|NONE|chance(75.0)
RuinsCandleSconceOn2|RuinsCandleSconceOff01|NONE|chance(75.0)

[Forms|HighGateRuinsLocation]
RuinsFloorCandleLampSmallOn|RuinsFloorCandleLampSmallOff|NONE|chance(50.0)
RuinsFloorCandleLampSmallOn02|RuinsFloorCandleLampSmallOff02|NONE|chance(50.0)
RuinsFloorCandleLampMidOn|RuinsFloorCandleLampMidOff|NONE|chance(50.0)
RuinsFloorCandleLampMidOn02|RuinsFloorCandleLampMidOff02|NONE|chance(50.0)
RuinsCandleSconceOn2|RuinsCandleSconceOff01|NONE|chance(50.0)


[Forms|PotemasCatacombsLocation,ForelhostLocation]
ImpWallSconceCandle02|RuinsCandleSconceOff01|NONE|chance(75.0)

[Forms|WindhelmTempleOfTalosLocation]
CandleLanternwithCandle01|Lantern|NONE|chance(50.0)
GlazedCandlesStatic02|EmptyFX01


[References]
; Skyrim has a pretty bad problem with light bleeding
; through walls. Disable a few fixtures which would
; have made this problem worse.

; Extinguish candles in windhelm Hjerim which spoil secrets.
0x0DF722~Skyrim.esm|RuinsFloorCandleLampMidOff02
0x0DF723~Skyrim.esm|RuinsFloorCandleLampMidOff02

; Extinguish the glazed candlesticks in Winking Skeever hallway.
; These candles are problematic because they have so many addonNodes
; so close to each other. Since they can't cast shadows and the wall
; behind them is white, it's just ugly. Plus they bleed into the
; bedroom pretty severely.
0x0D4B2A~Skyrim.esm|RuinsFloorCandleLampSmallOff
0x0D4B2B~Skyrim.esm|RuinsFloorCandleLampSmallOff

; Upstairs winking skeever glazed candles, they bleed through floor
0x0D4ABB~Skyrim.esm|RuinsFloorCandleLampSmallOff

; Candlehearth Hall chandeliers cause overexposure, remove them
0x0CB96A~Skyrim.esm|EmptyFX01
0x0CB969~Skyrim.esm|EmptyFX01
0x0CB96B~Skyrim.esm|EmptyFX01

; Severin Manor in Raven Rock is overexposed by the crafting tables. Extinguish candles.
0x036DBA~Dragonborn.esm|EmptyFX01
0x036E1C~Dragonborn.esm|EmptyFX01
0x036E1D~Dragonborn.esm|EmptyFX01
0x036DB9~Dragonborn.esm|EmptyFX01

; Extinguish embers by statue of dibella, overexposed otherwise.
0x08D609~Skyrim.esm|FXfireWithEmbersOut
0x0CBC4A~Skyrim.esm|FXfireWithEmbersOut
